### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by LeifAndersen** [cosmez/racket-sdl#1]
Would it be possible for you to add a license for this project? Possible LGPL to match Racket's and SDL's license.

Thank you.

**Comment by cosmez** [comment]
Sure, ill do it when i get home.

**Comment by stonecauldron** [comment]
Any update on the license?

**Comment by LeifAndersen** [comment]
Oh cool, thank you for adding that. I am going to add this to the package server. If you want to maintain the link rather than me, ping me and I'll take it down so you can have it up there.

Thank you so much. :)
